default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: storage/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

production:
  <<: *default
  adapter: sqlite3
  database: storage/production.sqlite3

  cable:
    <<: *default
    adapter: sqlite3
    database: storage/cable_production.sqlite3
